task_contains() {
  local task_lc="$1"
  local pattern="$2"
  printf '%s' "$task_lc" | grep -Eq "$pattern"
}

stack_has() {
  local stack_csv="$1"
  local token="$2"
  printf ',%s,' "$stack_csv" | grep -q ",$token,"
}

detect_task_flags() {
  local task_lc="$1"
  local stack_csv="$2"
  local flags=()

  task_contains "$task_lc" 'issue|spec|acceptance criteria|gap analysis|missing|find gaps|дыры|слабые места|что плохо|легаси|что мешает' && flags+=("spec-driven")
  task_contains "$task_lc" 'comment|requirement|should|must|expected|meant for|supposed to|wrong|not right|instead of|copy|требован|должн|ожида|неправ|не так' && flags+=("requirement-check")
  task_contains "$task_lc" 'visual|layout|spacing|color|typography|hover|animation|responsive|ui polish|css' && flags+=("visual")
  task_contains "$task_lc" 'pr|pull request|review comment|code review|ci|review|audit|check quality|аудит|ревью|провер|проанализ|анализ|качество' && flags+=("review")
  task_contains "$task_lc" 'new api|schema|contract|migration|dependency|cross-system|cross system|parallel' && flags+=("contract")
  task_contains "$task_lc" 'n8n|workflow' && flags+=("n8n")
  task_contains "$task_lc" 'ai|llm|rag|prompt|vector|agent|multimodal' && flags+=("ai")
  task_contains "$task_lc" 'production|incident|outage|safety|guard|security' && flags+=("production")
  task_contains "$task_lc" 'framework gap|framework status|status.*framework|framework orchestration|orchestration audit|agent quality|human-like|human like|senior engineer agent|production readiness|operating model|orchestration redesign|skill architecture|runtime guard|выжимать.*codex|prompt coding|промпт[ -]?кодинг|фреймворк|фреймворка|оркестрац|агент|агентов|скил|скилл|автоматиз|лучше чем.*промпт|все ли автоматиз' && flags+=("strategic")
  stack_has "$stack_csv" "playwright" && flags+=("playwright")

  if [ "${#flags[@]}" -eq 0 ]; then
    printf 'none\n'
  else
    join_by "," "${flags[@]}"
    printf '\n'
  fi
}

requires_requirement_check() {
  local task_lc="$1"
  task_contains "$task_lc" 'comment|requirement|should|must|expected|meant for|supposed to|wrong|not right|instead of|acceptance criteria|issue|spec|copy'
}

is_generic_task() {
  local task_lc="$1"
  task_contains "$task_lc" 'review the app|review codebase|audit codebase|check for issues|find gaps|production readiness|framework gaps'
}

skill_exists() {
  local skill="$1"
  [ -f "$(framework_root)/skills/$skill/SKILL.md" ]
}

append_unique_csv() {
  local csv="$1"
  local value="$2"
  local item
  [ -n "$value" ] || {
    printf '%s\n' "$csv"
    return 0
  }
  IFS=',' read -r -a existing_items <<< "$csv"
  for item in "${existing_items[@]-}"; do
    item="$(printf '%s' "$item" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [ "$item" = "$value" ] && {
      printf '%s\n' "$csv"
      return 0
    }
  done
  if [ -z "$csv" ]; then
    printf '%s\n' "$value"
  else
    printf '%s,%s\n' "$csv" "$value"
  fi
}

classify_task_shape() {
  local task_lc="$1"
  if task_contains "$task_lc" 'typo|copy change|text swap|rename|small config|single-file|single file|one file|mechanical|token swap'; then
    printf 'mechanical\n'
  elif task_contains "$task_lc" 'framework gap|framework status|status.*framework|статус.*фреймвор|production readiness|roadmap|design philosophy|long-term|migration|cross-system|cross system|orchestration|выжимать.*codex|prompt coding|промпт[ -]?кодинг|фреймворк|фреймворка|оркестрац|агент|агентов|скил|скилл|комплексн.*аудит|слабые места|дыры|что плохо|что мешает|лучше чем.*промпт|все ли автоматиз|качество.*скил'; then
    printf 'strategic\n'
  elif task_contains "$task_lc" 'review|audit|check|verify|аудит|ревью|провер|проанализ|анализ|качество'; then
    printf 'review\n'
  else
    printf 'implementation\n'
  fi
}

scan_text_for_policy_violations() {
  local content="$1"
  local findings=""

  if printf '%s' "$content" | grep -Eq 'AKIA[0-9A-Z]{16}'; then
    findings="$(append_unique_csv "$findings" "hardcoded-aws-key")"
  fi
  if printf '%s' "$content" | grep -Eq 'sk-(proj|org|svcacct)-[A-Za-z0-9_-]{20,}'; then
    findings="$(append_unique_csv "$findings" "hardcoded-openai-key")"
  fi
  if printf '%s' "$content" | grep -Eq 'sk-ant-[A-Za-z0-9-]{20,}'; then
    findings="$(append_unique_csv "$findings" "hardcoded-anthropic-key")"
  fi
  if printf '%s' "$content" | grep -Eq 'AIza[0-9A-Za-z_-]{35}'; then
    findings="$(append_unique_csv "$findings" "hardcoded-google-key")"
  fi
  if printf '%s' "$content" | grep -Eqi '(password|pwd)[[:space:]]*[:=][[:space:]]*["'\''][^"'\'']{4,}["'\'']'; then
    findings="$(append_unique_csv "$findings" "inline-password")"
  fi
  if printf '%s' "$content" | grep -Eq 'https?://[^[:space:]/:@]+:[^[:space:]@]+@'; then
    findings="$(append_unique_csv "$findings" "embedded-url-credentials")"
  fi
  local attribution_pattern='co-authored''-by:|generated by chat''gpt|generated by clau''de|generated with a''i'
  if printf '%s' "$content" | grep -Eqi "$attribution_pattern"; then
    findings="$(append_unique_csv "$findings" "ai-attribution")"
  fi

  printf '%s\n' "${findings:-none}"
}

ensure_project_git_hooks() {
  local root="${1:-$(project_root)}"
  local hooks_dir
  if git -C "$root" rev-parse --show-toplevel >/dev/null 2>&1; then
    hooks_dir="$(
      cd "$root"
      common_dir="$(git rev-parse --git-common-dir)"
      mkdir -p "$common_dir/hooks"
      cd "$common_dir/hooks"
      pwd
    )"
  else
    hooks_dir="$root/.git/hooks"
    mkdir -p "$hooks_dir"
  fi
  printf '%s\n' "$hooks_dir"
}

detect_missing_deps() {
  local missing=""
  has_command codex || missing="$(append_unique_csv "$missing" "codex")"
  has_command rg || missing="$(append_unique_csv "$missing" "ripgrep")"
  has_command gh || missing="$(append_unique_csv "$missing" "gh")"
  has_command jq || missing="$(append_unique_csv "$missing" "jq")"
  printf '%s\n' "${missing:-none}"
}

cache_read() {
  local name="$1"
  local file
  file="$(project_cache_dir)/$name"
  [ -f "$file" ] || return 1
  cat "$file"
}

cache_write() {
  local name="$1"
  shift
  ensure_cache_dir
  printf '%s\n' "$*" > "$(project_cache_dir)/$name"
}

cached_stack_summary() {
  local detected
  detected="$(bash "$(framework_root)/scripts/detect-project-stack.sh" "$(project_root)")"
  cache_write stack.txt "$detected"
  printf '%s\n' "$detected"
}

cached_feature_summary() {
  local detected
  detected="$(bash "$(framework_root)/scripts/detect-project-features.sh" "$(project_root)")"
  cache_write features.txt "$detected"
  printf '%s\n' "$detected"
}

cached_policy_summary() {
  local detected
  detected="$(bash "$(framework_root)/scripts/detect-project-policy.sh" "$(project_root)")"
  cache_write policy.txt "$detected"
  printf '%s\n' "$detected"
}

cached_convention_summary() {
  local detected
  detected="$(bash "$(framework_root)/scripts/detect-project-conventions.sh" "$(project_root)")"
  cache_write conventions.txt "$detected"
  printf '%s\n' "$detected"
}

cached_repo_intelligence_file() {
  local file
  file="$(project_cache_dir)/repo-intelligence.env"
  if [ ! -f "$file" ] || repo_intelligence_stale "$file"; then
    bash "$(framework_root)/scripts/detect-repo-intelligence.sh" "$(project_root)" > "$file"
  fi
  printf '%s\n' "$file"
}

refresh_repo_intelligence() {
  local file
  file="$(project_cache_dir)/repo-intelligence.env"
  bash "$(framework_root)/scripts/detect-repo-intelligence.sh" "$(project_root)" > "$file"
  printf '%s\n' "$file"
}

repo_intelligence_stale() {
  local file="$1"
  local expected actual
  [ -f "$file" ] || return 0
  expected="$(repo_intelligence_fingerprint)"
  actual="$(sed -n 's/^RI_FINGERPRINT=//p' "$file" | tail -n 1)"
  actual="${actual#\'}"
  actual="${actual%\'}"
  [ -n "$actual" ] || return 0
  [ "$expected" != "$actual" ]
}

repo_intelligence_summary() {
  load_repo_intelligence
  printf 'framework=%s\n' "$RI_PRIMARY_FRAMEWORK"
  printf 'stack=%s\n' "$RI_STACK"
  printf 'features=%s\n' "$RI_FEATURES"
  printf 'policy=%s\n' "$RI_POLICY"
  printf 'domain_hints=%s\n' "$RI_DOMAIN_HINTS"
  printf 'refreshed_at=%s\n' "${RI_REFRESHED_AT:-unknown}"
  printf 'fingerprint=%s\n' "${RI_FINGERPRINT:-unknown}"
}

load_repo_intelligence() {
  local file
  file="$(cached_repo_intelligence_file)"
  # shellcheck disable=SC1090
  . "$file"
  : "${RI_STACK:=unknown}"
  : "${RI_FEATURES:=none}"
  : "${RI_POLICY:=none}"
  : "${RI_CONVENTIONS:=none}"
  : "${RI_PRIMARY_FRAMEWORK:=unknown}"
  : "${RI_FRONTEND_SYSTEM:=unknown}"
  : "${RI_BACKEND_SYSTEM:=unknown}"
  : "${RI_TEST_SYSTEM:=unknown}"
  : "${RI_DOMAIN_HINTS:=core}"
}

detect_task_intent() {
  local task_lc="$1"
  if task_contains "$task_lc" '(^|[^a-z])(review|audit|findings|comment)([^a-z]|$)|pr review|review comment|аудит|ревью|проверка|проанализируй|анализ'; then
    printf 'review\n'
  elif task_contains "$task_lc" 'test|coverage|regression|e2e|тест|покрытие|регресс'; then
    printf 'test\n'
  elif task_contains "$task_lc" 'refactor|simplify|migrate|clean up|modernize|рефактор|упрости|миграц|модерниз'; then
    printf 'refactor\n'
  elif task_contains "$task_lc" 'bug|fix|crash|wrong behavior|debug|incident|failure|performance|баг|почини|исправь|сломал|ошибк|инцидент|производительн'; then
    printf 'fix\n'
  elif task_contains "$task_lc" 'design|architecture|schema|contract|technical plan|dependency|архитект|схем|контракт|технический план|зависимост'; then
    printf 'design\n'
  elif task_contains "$task_lc" 'estimate|proposal|scope|cost|оценк|смет|стоимост|скоуп'; then
    printf 'estimate\n'
  elif task_contains "$task_lc" 'backlog|sprint|milestone|ticket|repo setup|create pr|open pr|создай pr|создать pr|открой pr|пулл реквест|беклог|спринт|тикет|задач'; then
    printf 'manage\n'
  else
    printf 'implement\n'
  fi
}

choose_role_from_repo_intelligence() {
  local task_lc="$1"
  local shape="$2"
  local intent
  load_repo_intelligence
  intent="$(detect_task_intent "$task_lc")"

  if task_contains "$task_lc" 'framework health|new skill|role update|routing|codex framework|framework gap|framework orchestration|orchestration audit|agent quality|human-like|human like|senior engineer agent|production readiness|operating model|orchestration redesign|skill architecture|runtime guard|codex hook|codex hooks|hook-native|runtime hook|lifecycle automation|хуки|хук|фреймворк|фреймворка|оркестрац|агент|агентов|доменные знания|валидац.*фреймворк'; then
    printf 'framework-manager\n'
    return 0
  fi
  if task_contains "$task_lc" 'dependency audit|security audit|cve|plugin review'; then
    printf 'auditor\n'
    return 0
  fi
  case "$intent" in
    manage) printf 'project-manager\n'; return 0 ;;
    estimate) printf 'estimator\n'; return 0 ;;
    review) printf 'reviewer\n'; return 0 ;;
    test) printf 'tester\n'; return 0 ;;
    refactor) printf 'refactorer\n'; return 0 ;;
    design) printf 'architect\n'; return 0 ;;
  esac

  if task_contains "$task_lc" 'n8n|workflow node|workflow retry|webhook chain'; then
    printf 'builder-n8n\n'
    return 0
  fi
  if task_contains "$task_lc" ' llm|^llm| ai |^ai |rag|prompt|vector|agent|multimodal|chatbot'; then
    printf 'builder-ai\n'
    return 0
  fi
  if task_contains "$task_lc" 'automation|workflow'; then
    printf 'builder-automation\n'
    return 0
  fi
  if task_contains "$task_lc" 'docker|kubernetes|infra|deploy|ci|cd'; then
    printf 'builder-infra\n'
    return 0
  fi
  if { [ "$RI_PRIMARY_FRAMEWORK" = "nextjs" ] || [ "$RI_PRIMARY_FRAMEWORK" = "blazor" ] || task_contains "$task_lc" 'next\.js|nextjs|blazor'; } \
    && task_contains "$task_lc" 'route handler|server action|app router|razor|page and api|full-stack framework|full stack'; then
    printf 'builder-fullstack\n'
    return 0
  fi
  if task_contains "$task_lc" 'react native|expo|flutter|native app|mobile app|ios|android'; then
    printf 'builder-mobile\n'
    return 0
  fi
  if task_contains "$task_lc" 'mobile' && printf '%s' "$RI_DOMAIN_HINTS" | grep -Eq '(^|,)mobile(,|$)'; then
    printf 'builder-mobile\n'
    return 0
  fi
  if task_contains "$task_lc" 'mobile menu|mobile nav|mobile drawer|mobile sidebar|mobile overlay|mobile sheet|mobile dialog|mobile dropdown' \
    && { [ "$RI_PRIMARY_FRAMEWORK" = "nextjs" ] || [ "$RI_PRIMARY_FRAMEWORK" = "react" ] || [ "$RI_PRIMARY_FRAMEWORK" = "vue" ] || [ "$RI_PRIMARY_FRAMEWORK" = "angular" ] || [ "$RI_PRIMARY_FRAMEWORK" = "blazor" ]; }; then
    case "$intent" in
      fix) printf 'fixer\n' ;;
      *) printf 'builder-frontend\n' ;;
    esac
    return 0
  fi
  if printf '%s' "$RI_DOMAIN_HINTS" | grep -Eq '(^|,)mobile(,|$)'; then
    printf 'builder-mobile\n'
    return 0
  fi
  if task_contains "$task_lc" 'ui|component|page|frontend|styling|form|accessibility|avatar|image|hero|section|copy|landing'; then
    case "$intent" in
      fix) printf 'fixer\n' ;;
      *) printf 'builder-frontend\n' ;;
    esac
    return 0
  fi
  if task_contains "$task_lc" 'api|backend|service|auth|job|database|persistence|query|endpoint'; then
    case "$intent" in
      fix) printf 'fixer\n' ;;
      *) printf 'builder-backend\n' ;;
    esac
    return 0
  fi
  if [ "$RI_PRIMARY_FRAMEWORK" = "nextjs" ] || [ "$RI_PRIMARY_FRAMEWORK" = "react" ] || [ "$RI_PRIMARY_FRAMEWORK" = "vue" ] || [ "$RI_PRIMARY_FRAMEWORK" = "angular" ]; then
    case "$intent" in
      fix) printf 'fixer\n' ;;
      *) printf 'builder-frontend\n' ;;
    esac
    return 0
  fi
  if [ "$RI_BACKEND_SYSTEM" != "unknown" ]; then
    case "$intent" in
      fix) printf 'fixer\n' ;;
      *) printf 'builder-backend\n' ;;
    esac
    return 0
  fi
  printf 'builder\n'
}

choose_tier_from_role_and_task() {
  local role="$1"
  local task_lc="$2"
  local shape="$3"
  local contract_task="no"
  local tier="medium"
  if task_contains "$task_lc" 'new api|schema|contract|migration|dependency|cross-system|cross system|parallel'; then
    contract_task="yes"
  fi
  [ "$shape" = "mechanical" ] && [ "$contract_task" = "no" ] && tier="low"
  case "$role" in
    estimator)
      tier="medium"
      ;;
    framework-manager)
      if task_contains "$task_lc" 'framework gap|framework status|status.*framework|framework orchestration|orchestration audit|agent quality|human-like|human like|senior engineer agent|production readiness|operating model|orchestration redesign|skill architecture|runtime guard|codex hook|codex hooks|hook-native|runtime hook|lifecycle automation|хуки|хук|выжимать.*codex|prompt coding|промпт[ -]?кодинг|статус.*фреймвор|оркестрац|агент|агентов|доменные знания|валидац.*фреймворк'; then
        tier="xhigh"
      else
        tier="high"
      fi
      ;;
    architect|builder-fullstack|builder-ai|builder-n8n|builder-automation|refactorer)
      tier="high"
      ;;
    project-manager)
      if task_contains "$task_lc" 'create pr|open pr|publish pr|pr body|release summary|commit|stage changes|git status|push branch|создай pr|создать pr|открой pr|пулл реквест|коммит'; then
        tier="low"
      else
        tier="medium"
      fi
      ;;
    fixer)
      tier="medium"
      task_contains "$task_lc" 'across|cross-system|cross system|multi-system|multi service|migration|webhook|concurrency|deadlock|race condition|distributed' && tier="high"
      [ "$shape" = "mechanical" ] && [ "$contract_task" = "no" ] && tier="low"
      ;;
    reviewer|tester|builder-frontend|builder-backend|builder-infra|builder-mobile|builder|auditor)
      [ "$tier" = "low" ] || tier="medium"
      ;;
  esac
  if [ "$contract_task" = "yes" ] && [ "$tier" != "xhigh" ] && [ "$role" != "estimator" ]; then
    tier="high"
  fi
  printf '%s\n' "$tier"
}

infer_domains_for_task() {
  local role="$1"
  local task_lc="$2"
  local stack_csv="$3"
  local domains=""

  add_domain() {
    local domain="$1"
    domains="$(append_unique_csv "$domains" "$domain")"
  }

  case "$role" in
    builder-frontend|reviewer)
      if task_contains "$task_lc" 'ui|frontend|component|page|style|css|layout|accessibility|responsive|visual|avatar|image|hero|section|copy|text|landing'; then
        add_domain "frontend"
      fi
      if task_contains "$task_lc" 'api|backend|service|database|query|endpoint|auth'; then
        add_domain "backend"
      fi
      ;;
    builder-backend|architect|fixer|refactorer|builder)
      if task_contains "$task_lc" 'ui|frontend|component|page|style|css|layout|accessibility|responsive|visual|avatar|image|hero|section|copy|text|landing'; then
        add_domain "frontend"
      fi
      if task_contains "$task_lc" 'api|backend|service|database|query|endpoint|auth|migration|job'; then
        add_domain "backend"
      fi
      ;;
    builder-mobile)
      add_domain "mobile"
      ;;
    builder-infra)
      add_domain "infra"
      ;;
    builder-automation|builder-ai|builder-n8n|builder-fullstack)
      add_domain "specialized"
      ;;
    tester)
      add_domain "testing"
      ;;
    auditor|project-manager|framework-manager|estimator)
      add_domain "core"
      ;;
  esac

  stack_has "$stack_csv" "react" && add_domain "frontend"
  stack_has "$stack_csv" "vue" && add_domain "frontend"
  stack_has "$stack_csv" "angular" && add_domain "frontend"
  stack_has "$stack_csv" "nextjs" && add_domain "specialized"
  stack_has "$stack_csv" "dotnet" && add_domain "backend"
  stack_has "$stack_csv" "blazor" && add_domain "specialized"
  stack_has "$stack_csv" "flutter" && add_domain "mobile"
  stack_has "$stack_csv" "react-native" && add_domain "mobile"

  if [ -z "$domains" ]; then
    case "$role" in
      tester) domains="testing" ;;
      builder-infra) domains="infra" ;;
      builder-mobile) domains="mobile" ;;
      builder-automation|builder-ai|builder-n8n|builder-fullstack) domains="specialized" ;;
      builder-frontend) domains="frontend" ;;
      builder-backend|architect|builder)
        if task_contains "$task_lc" 'ui|frontend|component|page|style|css|layout|accessibility|responsive|visual|avatar|image|hero|section|copy|text|landing'; then
          domains="frontend"
        else
          domains="backend"
        fi
        ;;
      fixer|refactorer|reviewer)
        if task_contains "$task_lc" 'ui|frontend|component|page|style|css|layout|accessibility|responsive|visual|avatar|image|hero|section|copy|text|landing'; then
          domains="frontend"
        else
          domains="backend"
        fi
        ;;
      *) domains="core" ;;
    esac
  fi

  if [ "$domains" != "core" ]; then
    domains="$(append_unique_csv "$domains" "core")"
  fi

  printf '%s\n' "$domains"
}

skill_map_path() {
  local domain="$1"
  printf '%s/SKILLS_MAP.%s.md\n' "$(framework_root)" "$domain"
}

resolve_skills_from_map() {
  local map_file="$1"
  local task_lc="$2"
  [ -f "$map_file" ] || return 0
  awk -F'|' '
    /^\| `/ {
      skill=$2; keywords=$3
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", skill)
      gsub(/`/, "", skill)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", keywords)
      print skill "|" keywords
    }
  ' "$map_file" | while IFS='|' read -r skill keywords; do
    [ -n "$skill" ] || continue
    keyword_regex="$(printf '%s' "$keywords" | sed 's/, /|/g; s/,/|/g')"
    if printf '%s' "$task_lc" | grep -Eqi "$keyword_regex"; then
      printf '%s\n' "$skill"
    fi
  done
}

resolve_skills_for_domains() {
  local domains_csv="$1"
  local task_lc="$2"
  local domain skill resolved=""
  IFS=',' read -r -a domains_arr <<< "$domains_csv"
  for domain in "${domains_arr[@]}"; do
    domain="$(printf '%s' "$domain" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [ -n "$domain" ] || continue
    while IFS= read -r skill; do
      [ -n "$skill" ] || continue
      resolved="$(append_unique_csv "$resolved" "$skill")"
    done <<EOF
$(resolve_skills_from_map "$(skill_map_path "$domain")" "$task_lc")
EOF
  done
  printf '%s\n' "${resolved:-none}"
}

feature_to_skills() {
  local feature="$1"
  case "$feature" in
    dark-mode) printf 'dark-mode\n' ;;
    pwa) printf 'pwa-implementation\n' ;;
    i18n) printf 'i18n-implementation\n' ;;
    analytics) printf 'analytics-implementation\n' ;;
    error-tracking) printf 'error-tracking\n' ;;
    feature-flags) printf 'feature-flags\n' ;;
    background-jobs) printf 'background-jobs\n' ;;
    realtime) printf 'websocket-realtime\n' ;;
    search) printf 'search-implementation\n' ;;
    uploads) printf 'file-upload-storage\n' ;;
    email) printf 'email-notifications\n' ;;
    push) printf 'push-notifications\n' ;;
    offline-sync) printf 'offline-sync-design\n' ;;
    video) printf 'video-streaming\n' ;;
    caching) printf 'caching-strategy\n' ;;
    database-orm) printf 'database-migration\ndatabase-optimization\n' ;;
    resilience) printf 'resilience-patterns\n' ;;
    stripe) printf 'payment-integration\nsaas-billing-portal\n' ;;
    auth) printf 'auth-security\nsaas-onboarding\n' ;;
    graphql) printf 'graphql-design\ngraphql-implement\n' ;;
    message-queue) printf 'message-queue-patterns\n' ;;
    observability) printf 'observability-design\n' ;;
    rate-limiting) printf 'rate-limiting\n' ;;
    firebase) printf 'firebase-patterns\n' ;;
    reporting) printf 'reporting-dashboards\n' ;;
    state-management) printf 'state-management\n' ;;
    forms) printf 'advanced-forms\n' ;;
    motion) printf 'animation-motion\n' ;;
    advanced-animation) printf 'advanced-animation\n' ;;
    design-system) printf 'design-system-implement\n' ;;
    tailwind) printf 'design-system-implement\nui-consistency-audit\nresponsive-design\n' ;;
    variants) printf 'design-system-implement\n' ;;
    ui-primitives) printf 'design-system-implement\nui-consistency-audit\n' ;;
  esac
}

resolve_feature_skills() {
  local features_csv="$1"
  local resolved="" feature skill
  IFS=',' read -r -a features_arr <<< "$features_csv"
  for feature in "${features_arr[@]}"; do
    feature="$(printf '%s' "$feature" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [ -n "$feature" ] || continue
    while IFS= read -r skill; do
      [ -n "$skill" ] || continue
      resolved="$(append_unique_csv "$resolved" "$skill")"
    done <<EOF
$(feature_to_skills "$feature")
EOF
  done
  printf '%s\n' "${resolved:-none}"
}

csv_contains() {
  local csv="$1"
  local value="$2"
  printf ',%s,' "$csv" | grep -q ",$value,"
}

resolve_domain_baseline_skills() {
  local role="$1"
  local domains_csv="$2"
  local resolved=""

  if csv_contains "$domains_csv" "frontend"; then
    case "$role" in
      builder-frontend|builder|builder-fullstack|fixer|refactorer|reviewer|architect)
        resolved="$(append_unique_csv "$resolved" "frontend-implement")"
        resolved="$(append_unique_csv "$resolved" "responsive-design")"
        resolved="$(append_unique_csv "$resolved" "design-system-implement")"
        resolved="$(append_unique_csv "$resolved" "animation-motion")"
        resolved="$(append_unique_csv "$resolved" "ui-consistency-audit")"
        ;;
    esac
    case "$role" in
      builder-frontend|builder|builder-fullstack|fixer|refactorer)
        resolved="$(append_unique_csv "$resolved" "accessibility-implement")"
        resolved="$(append_unique_csv "$resolved" "seo-optimization")"
        ;;
      reviewer|architect)
        resolved="$(append_unique_csv "$resolved" "accessibility-audit")"
        resolved="$(append_unique_csv "$resolved" "seo-audit")"
        resolved="$(append_unique_csv "$resolved" "ui-consistency-audit")"
        resolved="$(append_unique_csv "$resolved" "frontend-review")"
        ;;
      tester)
        resolved="$(append_unique_csv "$resolved" "frontend-test")"
        ;;
    esac
  fi

  if csv_contains "$domains_csv" "backend"; then
    case "$role" in
      builder-backend|builder|builder-fullstack|fixer|refactorer|reviewer|architect)
        resolved="$(append_unique_csv "$resolved" "backend-implement")"
        resolved="$(append_unique_csv "$resolved" "api-design")"
        resolved="$(append_unique_csv "$resolved" "data-validation-design")"
        resolved="$(append_unique_csv "$resolved" "auth-security")"
        resolved="$(append_unique_csv "$resolved" "database-migration")"
        resolved="$(append_unique_csv "$resolved" "database-optimization")"
        resolved="$(append_unique_csv "$resolved" "docs-sync")"
        resolved="$(append_unique_csv "$resolved" "observability-design")"
        ;;
      tester)
        resolved="$(append_unique_csv "$resolved" "backend-test")"
        ;;
      reviewer|architect)
        resolved="$(append_unique_csv "$resolved" "backend-review")"
        ;;
    esac
  fi

  if csv_contains "$domains_csv" "mobile"; then
    case "$role" in
      builder-mobile|fixer|refactorer|reviewer|architect)
        resolved="$(append_unique_csv "$resolved" "mobile-implement")"
        resolved="$(append_unique_csv "$resolved" "accessibility-implement")"
        resolved="$(append_unique_csv "$resolved" "animation-motion")"
        resolved="$(append_unique_csv "$resolved" "mobile-deployment")"
        resolved="$(append_unique_csv "$resolved" "deployment-validation")"
        resolved="$(append_unique_csv "$resolved" "offline-sync-design")"
        resolved="$(append_unique_csv "$resolved" "auth-security")"
        ;;
      tester)
        resolved="$(append_unique_csv "$resolved" "mobile-test")"
        ;;
      reviewer|architect)
        resolved="$(append_unique_csv "$resolved" "mobile-review")"
        resolved="$(append_unique_csv "$resolved" "accessibility-audit")"
        ;;
    esac
  fi

  if csv_contains "$domains_csv" "infra"; then
    resolved="$(append_unique_csv "$resolved" "devops-ci")"
    resolved="$(append_unique_csv "$resolved" "infrastructure-as-code")"
    resolved="$(append_unique_csv "$resolved" "deployment-validation")"
    case "$role" in
      builder-infra|architect|reviewer|fixer)
        resolved="$(append_unique_csv "$resolved" "deployment-strategies")"
        resolved="$(append_unique_csv "$resolved" "environment-management")"
        resolved="$(append_unique_csv "$resolved" "kubernetes-workload")"
        resolved="$(append_unique_csv "$resolved" "observability-design")"
        resolved="$(append_unique_csv "$resolved" "incident-response")"
        ;;
    esac
  fi

  if csv_contains "$domains_csv" "specialized"; then
    case "$role" in
      builder-ai)
        resolved="$(append_unique_csv "$resolved" "automation-ai-workflows")"
        resolved="$(append_unique_csv "$resolved" "llm-security")"
        resolved="$(append_unique_csv "$resolved" "ai-agent-architecture")"
        resolved="$(append_unique_csv "$resolved" "prompt-management")"
        resolved="$(append_unique_csv "$resolved" "rag-pipeline")"
        resolved="$(append_unique_csv "$resolved" "vector-database")"
        resolved="$(append_unique_csv "$resolved" "ai-streaming")"
        resolved="$(append_unique_csv "$resolved" "multimodal-processing")"
        ;;
      builder-n8n)
        resolved="$(append_unique_csv "$resolved" "automation-n8n-implement")"
        resolved="$(append_unique_csv "$resolved" "automation-n8n-architecture")"
        resolved="$(append_unique_csv "$resolved" "automation-n8n-debug")"
        resolved="$(append_unique_csv "$resolved" "n8n-test")"
        resolved="$(append_unique_csv "$resolved" "llm-security")"
        resolved="$(append_unique_csv "$resolved" "prompt-management")"
        ;;
      builder-automation)
        resolved="$(append_unique_csv "$resolved" "automation-ai-workflows")"
        resolved="$(append_unique_csv "$resolved" "llm-security")"
        resolved="$(append_unique_csv "$resolved" "automation-n8n-architecture")"
        resolved="$(append_unique_csv "$resolved" "automation-n8n-debug")"
        resolved="$(append_unique_csv "$resolved" "n8n-test")"
        resolved="$(append_unique_csv "$resolved" "prompt-management")"
        resolved="$(append_unique_csv "$resolved" "rag-pipeline")"
        resolved="$(append_unique_csv "$resolved" "vector-database")"
        ;;
      builder-fullstack)
        resolved="$(append_unique_csv "$resolved" "frontend-implement")"
        resolved="$(append_unique_csv "$resolved" "backend-implement")"
        resolved="$(append_unique_csv "$resolved" "api-design")"
        resolved="$(append_unique_csv "$resolved" "accessibility-implement")"
        resolved="$(append_unique_csv "$resolved" "data-validation-design")"
        resolved="$(append_unique_csv "$resolved" "docs-sync")"
        ;;
    esac
  fi

  if csv_contains "$domains_csv" "core"; then
    case "$role" in
      framework-manager)
        resolved="$(append_unique_csv "$resolved" "framework-management")"
        resolved="$(append_unique_csv "$resolved" "framework-orchestration-audit")"
        resolved="$(append_unique_csv "$resolved" "docs-sync")"
        ;;
      auditor)
        resolved="$(append_unique_csv "$resolved" "security-audit")"
        resolved="$(append_unique_csv "$resolved" "dependency-audit")"
        resolved="$(append_unique_csv "$resolved" "audit-logging")"
        resolved="$(append_unique_csv "$resolved" "incident-response")"
        ;;
      project-manager|estimator)
        resolved="$(append_unique_csv "$resolved" "process-hygiene")"
        resolved="$(append_unique_csv "$resolved" "project-setup")"
        resolved="$(append_unique_csv "$resolved" "release-management")"
        resolved="$(append_unique_csv "$resolved" "adr-management")"
        resolved="$(append_unique_csv "$resolved" "docs-sync")"
        ;;
      architect)
        resolved="$(append_unique_csv "$resolved" "adr-management")"
        resolved="$(append_unique_csv "$resolved" "security-audit")"
        resolved="$(append_unique_csv "$resolved" "observability-design")"
        ;;
    esac
  fi

  printf '%s\n' "${resolved:-none}"
}

resolve_stack_skills() {
  local role="$1"
  local stack_csv="$2"
  local resolved=""

  if stack_has "$stack_csv" "react"; then
    case "$role" in
      builder-frontend|builder|builder-fullstack|fixer|refactorer|reviewer|architect) resolved="$(append_unique_csv "$resolved" "frontend-implement-react")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "frontend-test-react")" ;;
    esac
  fi
  if stack_has "$stack_csv" "vue"; then
    case "$role" in
      builder-frontend|builder|fixer|refactorer|reviewer|architect) resolved="$(append_unique_csv "$resolved" "frontend-implement-vue")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "frontend-test-vue")" ;;
    esac
  fi
  if stack_has "$stack_csv" "angular"; then
    case "$role" in
      builder-frontend|builder|fixer|refactorer|reviewer|architect) resolved="$(append_unique_csv "$resolved" "frontend-implement-angular")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "frontend-test-angular")" ;;
    esac
  fi
  if stack_has "$stack_csv" "nextjs"; then
    case "$role" in
      builder-fullstack|builder|architect|reviewer|builder-ai|builder-automation) resolved="$(append_unique_csv "$resolved" "fullstack-nextjs-implement")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "fullstack-nextjs-test")" ;;
    esac
  fi
  if stack_has "$stack_csv" "tailwind"; then
    case "$role" in
      builder-frontend|builder|builder-fullstack|fixer|refactorer|reviewer|architect)
        resolved="$(append_unique_csv "$resolved" "design-system-implement")"
        resolved="$(append_unique_csv "$resolved" "ui-consistency-audit")"
        ;;
    esac
  fi
  if stack_has "$stack_csv" "dotnet"; then
    case "$role" in
      builder-backend|builder|builder-fullstack|architect|reviewer|fixer|refactorer) resolved="$(append_unique_csv "$resolved" "backend-implement-dotnet")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "backend-test-dotnet")" ;;
    esac
  fi
  if stack_has "$stack_csv" "nestjs"; then
    case "$role" in
      builder-backend|builder|architect|reviewer|fixer|refactorer) resolved="$(append_unique_csv "$resolved" "backend-implement-nestjs")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "backend-test-nestjs")" ;;
    esac
  fi
  if stack_has "$stack_csv" "typescript" && ! stack_has "$stack_csv" "nestjs" && ! stack_has "$stack_csv" "dotnet" && ! stack_has "$stack_csv" "nextjs"; then
    case "$role" in
      builder-backend|builder|architect|reviewer|fixer|refactorer) resolved="$(append_unique_csv "$resolved" "backend-implement-node")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "backend-test-node")" ;;
    esac
  fi
  if stack_has "$stack_csv" "flutter"; then
    case "$role" in
      builder-mobile|fixer|refactorer|reviewer|architect) resolved="$(append_unique_csv "$resolved" "mobile-implement-flutter")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "mobile-test-flutter")" ;;
    esac
  fi
  if stack_has "$stack_csv" "react-native"; then
    case "$role" in
      builder-mobile|fixer|refactorer|reviewer|architect) resolved="$(append_unique_csv "$resolved" "mobile-implement-reactnative")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "mobile-test-reactnative")" ;;
    esac
  fi
  if stack_has "$stack_csv" "blazor"; then
    case "$role" in
      builder-fullstack|fixer|reviewer|architect) resolved="$(append_unique_csv "$resolved" "fullstack-blazor-implement")" ;;
      tester) resolved="$(append_unique_csv "$resolved" "fullstack-blazor-test")" ;;
    esac
  fi

  printf '%s\n' "${resolved:-none}"
}

merge_skill_csvs() {
  local merged="" csv item
  for csv in "$@"; do
    [ -n "$csv" ] || continue
    [ "$csv" = "none" ] && continue
    IFS=',' read -r -a items <<< "$csv"
    for item in "${items[@]}"; do
      item="$(printf '%s' "$item" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
      [ -n "$item" ] || continue
      skill_exists "$item" || continue
      merged="$(append_unique_csv "$merged" "$item")"
    done
  done
  printf '%s\n' "${merged:-none}"
}

csv_to_multiline() {
  local csv="$1" item
  [ "$csv" = "none" ] && return 0
  IFS=',' read -r -a items <<< "$csv"
  for item in "${items[@]}"; do
    item="$(printf '%s' "$item" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [ -n "$item" ] || continue
    printf '%s\n' "$item"
  done
}

model_retry_chain() {
  case "$1" in
    gpt-5.4-mini|gpt-5.1-codex-mini|codex-mini-latest) printf '%s,gpt-5.5\n' "$1" ;;
    gpt-5.5) printf 'gpt-5.5\n' ;;
    *) printf '%s\n' "$1" ;;
  esac
}
