#!/bin/bash
set -euo pipefail

. "$(dirname "$0")/lib.sh"

[ $# -ge 1 ] || fail "usage: commit-msg-check.sh <commit-message-file>"

message="$(cat "$1")"

if ! conventional_commit_valid "$message"; then
  fail "commit message must follow conventional commits"
fi

if printf '%s' "$message" | grep -Eqi 'co-authored-by:|generated by chatgpt|generated by claude|generated with ai'; then
  fail "commit message contains AI attribution"
fi
