#!/bin/bash
set -euo pipefail

. "$(dirname "$0")/lib.sh"

[ $# -ge 1 ] || fail "usage: commit-msg-check.sh <commit-message-file>"

message="$(cat "$1")"

if ! conventional_commit_valid "$message"; then
  fail "commit message must follow conventional commits"
fi

attribution_pattern='co-authored''-by:|generated by chat''gpt|generated by clau''de|generated with a''i'
if printf '%s' "$message" | grep -Eqi "$attribution_pattern"; then
  fail "commit message contains AI attribution"
fi
