#!/bin/bash
set -euo pipefail

. "$(dirname "$0")/lib.sh"

ROOT="${1:-$PWD}"
TASK="${2:-}"
refreshed_at="$(timestamp_utc)"
fingerprint="$(repo_intelligence_fingerprint "$ROOT")"

stack="$(bash "$(framework_root)/scripts/detect-project-stack.sh" "$ROOT" 2>/dev/null || echo "unknown")"
features="$(bash "$(framework_root)/scripts/detect-project-features.sh" "$ROOT" 2>/dev/null || echo "none")"
policy="$(bash "$(framework_root)/scripts/detect-project-policy.sh" "$ROOT" 2>/dev/null || echo "none")"
conventions="$(bash "$(framework_root)/scripts/detect-project-conventions.sh" "$ROOT" "$TASK" 2>/dev/null || echo "none")"
commands_file="$ROOT/.codex/project.env"

primary_framework="unknown"
frontend_system="unknown"
backend_system="unknown"
test_system="unknown"
domain_hints=""

stack_has "$stack" "nextjs" && primary_framework="nextjs"
stack_has "$stack" "react" && [ "$primary_framework" = "unknown" ] && primary_framework="react"
stack_has "$stack" "vue" && [ "$primary_framework" = "unknown" ] && primary_framework="vue"
stack_has "$stack" "angular" && [ "$primary_framework" = "unknown" ] && primary_framework="angular"
stack_has "$stack" "blazor" && primary_framework="blazor"
stack_has "$stack" "nestjs" && backend_system="nestjs"
stack_has "$stack" "dotnet" && [ "$backend_system" = "unknown" ] && backend_system="dotnet"
stack_has "$stack" "typescript" && [ "$backend_system" = "unknown" ] && backend_system="node"
stack_has "$stack" "tailwind" && frontend_system="tailwind"
printf '%s' "$policy" | grep -Eq '(^|,)tailwind-first(,|$)' && frontend_system="tailwind"
printf '%s' "$features" | grep -Eq '(^|,)design-system(,|$)|(^|,)ui-primitives(,|$)|(^|,)variants(,|$)' && [ "$frontend_system" = "unknown" ] && frontend_system="design-system"
stack_has "$stack" "unit-test" && test_system="unit-test"
stack_has "$stack" "testing-library" && test_system="testing-library"
printf '%s' "$policy" | grep -Eq '(^|,)tests-vitest(,|$)' && test_system="vitest"

stack_has "$stack" "react" && domain_hints="$(append_unique_csv "$domain_hints" "frontend")"
stack_has "$stack" "nextjs" && domain_hints="$(append_unique_csv "$domain_hints" "frontend")"
stack_has "$stack" "vue" && domain_hints="$(append_unique_csv "$domain_hints" "frontend")"
stack_has "$stack" "angular" && domain_hints="$(append_unique_csv "$domain_hints" "frontend")"
stack_has "$stack" "tailwind" && domain_hints="$(append_unique_csv "$domain_hints" "frontend")"
stack_has "$stack" "dotnet" && domain_hints="$(append_unique_csv "$domain_hints" "backend")"
stack_has "$stack" "nestjs" && domain_hints="$(append_unique_csv "$domain_hints" "backend")"
stack_has "$stack" "go" && domain_hints="$(append_unique_csv "$domain_hints" "backend")"
stack_has "$stack" "rust" && domain_hints="$(append_unique_csv "$domain_hints" "backend")"
stack_has "$stack" "flutter" && domain_hints="$(append_unique_csv "$domain_hints" "mobile")"
stack_has "$stack" "react-native" && domain_hints="$(append_unique_csv "$domain_hints" "mobile")"
printf '%s' "$features" | grep -Eq '(^|,)analytics(,|$)|(^|,)auth(,|$)|(^|,)forms(,|$)' && domain_hints="$(append_unique_csv "$domain_hints" "frontend")"
printf '%s' "$features" | grep -Eq '(^|,)database-orm(,|$)|(^|,)message-queue(,|$)|(^|,)graphql(,|$)|(^|,)rate-limiting(,|$)' && domain_hints="$(append_unique_csv "$domain_hints" "backend")"
printf '%s' "$features" | grep -Eq '(^|,)stripe(,|$)|(^|,)supabase(,|$)|(^|,)firebase(,|$)|(^|,)advanced-animation(,|$)' && domain_hints="$(append_unique_csv "$domain_hints" "specialized")"
[ -n "$domain_hints" ] || domain_hints="core"

printf 'RI_ROOT=%q\n' "$ROOT"
printf 'RI_REFRESHED_AT=%q\n' "$refreshed_at"
printf 'RI_FINGERPRINT=%q\n' "$fingerprint"
printf 'RI_STACK=%q\n' "$stack"
printf 'RI_FEATURES=%q\n' "$features"
printf 'RI_POLICY=%q\n' "$policy"
printf 'RI_CONVENTIONS=%q\n' "$conventions"
printf 'RI_PRIMARY_FRAMEWORK=%q\n' "$primary_framework"
printf 'RI_FRONTEND_SYSTEM=%q\n' "$frontend_system"
printf 'RI_BACKEND_SYSTEM=%q\n' "$backend_system"
printf 'RI_TEST_SYSTEM=%q\n' "$test_system"
printf 'RI_DOMAIN_HINTS=%q\n' "$domain_hints"
printf 'RI_COMMANDS_FILE=%q\n' "$commands_file"
